# Generated by Django 5.1.7 on 2025-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echographie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echographie',
            name='assistant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assistant(e)'),
        ),
    ]
