# Generated by Django 5.1.7 on 2025-06-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echographie', '0004_echographie_save_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='echographie',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
    ]
