# Generated by Django 5.1.7 on 2025-03-19 09:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('num_four', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(max_length=100, verbose_name='Nom du fourniseur')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('telephone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('num_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=100, verbose_name='Nom de produit')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='FacturePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de la création de la Facture')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('somme_verse', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme versée')),
                ('total_somme_verse', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total des sommes versées')),
                ('reste_a_payer', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer')),
                ('last_updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière mise à jour')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnels.personnel', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'FacturePharmacie',
                'verbose_name_plural': 'FacturePharmacies',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('num_com', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_commande', models.PositiveIntegerField(verbose_name='Quantité commande')),
                ('type_produit', models.CharField(max_length=100, verbose_name='Type de produit')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat unitaire")),
                ('total_achat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total achat')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de commande')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.fournisseur', verbose_name='Fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('num_stock', models.AutoField(primary_key=True, serialize=False)),
                ('type_produit', models.CharField(max_length=100, verbose_name='Type de produit')),
                ('quantite_reelle', models.PositiveIntegerField(default=0, verbose_name='Quantité réelle')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix total')),
                ('date_stock', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de stockage')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='pharmacie.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('num_vente', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_vendue', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité vendue')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix total')),
                ('date_vente', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de vente')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie.facturepharmacie', verbose_name='Facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='pharmacie.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
            },
        ),
    ]
