# Generated by Django 5.1.7 on 2025-03-19 23:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturepharmacie',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avance'),
        ),
        migrations.AddField(
            model_name='facturepharmacie',
            name='nombre_versements',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de paiements effectués'),
        ),
        migrations.AlterField(
            model_name='facturepharmacie',
            name='facture_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la Facture'),
        ),
        migrations.CreateModel(
            name='FactureAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant versé')),
                ('date_versement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='pharmacie.facturepharmacie', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
            },
        ),
    ]
