# Generated by Django 5.1.7 on 2025-03-20 08:17

import pharmacie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_facturepharmacie_avance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturepharmacie',
            name='numero_facture',
            field=models.CharField(default=pharmacie.models.generate_unique_numero_facture, max_length=25, unique=True, verbose_name='Numéro de dossier'),
        ),
    ]
