# Generated by Django 5.1.7 on 2025-03-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_alter_facturepharmacie_numero_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureavance',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='pharmacie.facturepharmacie', verbose_name='Numéro de Facture'),
        ),
    ]
