# Generated by Django 5.1.7 on 2025-03-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_alter_factureavance_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturepharmacie',
            name='numero_facture',
        ),
    ]
