# Generated by Django 5.1.7 on 2025-03-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0007_facturepharmacie_numero_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturepharmacie',
            name='paye',
        ),
        migrations.AddField(
            model_name='facturepharmacie',
            name='statut_paiement',
            field=models.CharField(choices=[('paye', 'Payée'), ('en_cours', 'En train de payer'), ('non_paye', 'Non payée')], default='non_paye', max_length=10),
        ),
    ]
