# Generated by Django 5.1.7 on 2025-03-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0008_remove_facturepharmacie_paye_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturepharmacie',
            name='statut_paiement',
        ),
        migrations.AddField(
            model_name='facturepharmacie',
            name='paye',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
