# Generated by Django 5.1.7 on 2025-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0009_remove_facturepharmacie_statut_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_admission',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'admission"),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
    ]
