# Generated by Django 5.1.7 on 2025-05-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0012_alter_commande_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='type_produit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='type_produit',
        ),
    ]
