# Generated by Django 5.1.7 on 2025-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0013_remove_commande_type_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantite_restante',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantité restante'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantite_vendue',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité vendue'),
        ),
    ]
