# Generated by Django 5.1.7 on 2025-04-29 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pharmacie_garde.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0009_patient_assistant_patient_medecin'),
        ('personnels', '0010_personnel_email'),
        ('pharmacie', '0009_remove_facturepharmacie_statut_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhGardeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100, verbose_name='Nom de produit')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'PhGardeProduit',
                'verbose_name_plural': 'PhGardeProduits',
            },
        ),
        migrations.CreateModel(
            name='PhGardeFacturePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(default=pharmacie_garde.models.generate_unique_numero_facture, max_length=25, unique=True, verbose_name='Numéro de facture')),
                ('facture_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la Facture')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('somme_verse', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme versée')),
                ('avance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avance')),
                ('total_somme_verse', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total des sommes versées')),
                ('reste_a_payer', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer')),
                ('nombre_versements', models.PositiveIntegerField(default=0, verbose_name='Nombre de paiements effectués')),
                ('last_updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière mise à jour')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnels.personnel', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'PhGardeFacturePharmacie',
                'verbose_name_plural': 'PhGardeFacturePharmacies',
            },
        ),
        migrations.CreateModel(
            name='PhGardeFactureAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant versé')),
                ('date_versement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='pharmacie_garde.phgardefacturepharmacie', verbose_name='Numéro de Facture')),
            ],
            options={
                'verbose_name': 'PhGardeAvance',
                'verbose_name_plural': 'PhGardeAvances',
            },
        ),
        migrations.CreateModel(
            name='PhGardeCommande',
            fields=[
                ('num_com', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_commande', models.PositiveIntegerField(verbose_name='Quantité commande')),
                ('type_produit', models.CharField(max_length=100, verbose_name='Type de produit')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat unitaire")),
                ('total_achat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total achat')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de commande')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.fournisseur', verbose_name='Fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie_garde.phgardeproduit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'PhGardeCommande',
                'verbose_name_plural': 'PhGardeCommandes',
            },
        ),
        migrations.CreateModel(
            name='PhGardeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(max_length=100, verbose_name='Type de produit')),
                ('quantite_reelle', models.PositiveIntegerField(default=0, verbose_name='Quantité réelle')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix total')),
                ('date_stock', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de stockage')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='pharmacie_garde.phgardeproduit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'PhGardeStock',
                'verbose_name_plural': 'PhGardeStocks',
            },
        ),
        migrations.CreateModel(
            name='PhGardeVente',
            fields=[
                ('num_stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_vendue', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité vendue')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix total')),
                ('date_vente', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de vente')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie_garde.phgardefacturepharmacie', verbose_name='Facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='pharmacie_garde.phgardeproduit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'PhGardeVente',
                'verbose_name_plural': 'PhGardeVentes',
            },
        ),
    ]
