# Generated by Django 5.1.7 on 2025-04-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_garde', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phgardevente',
            old_name='num_stock',
            new_name='num_vente',
        ),
    ]
