# Generated by Django 5.1.7 on 2025-05-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_garde', '0002_rename_num_stock_phgardevente_num_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='phgardecommande',
            name='date_admission',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'admission"),
        ),
        migrations.AddField(
            model_name='phgardecommande',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
    ]
