# Generated by Django 5.1.7 on 2025-05-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_garde', '0005_alter_phgardecommande_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phgardestock',
            name='type_produit',
        ),
    ]
