# Generated by Django 5.1.7 on 2025-05-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_garde', '0006_remove_phgardestock_type_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phgardecommande',
            name='type_produit',
        ),
    ]
