# Generated by Django 5.1.7 on 2025-05-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_garde', '0007_remove_phgardecommande_type_produit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phgardestock',
            options={'verbose_name': 'Stock de Garde', 'verbose_name_plural': 'Stocks de Garde'},
        ),
        migrations.AlterModelOptions(
            name='phgardevente',
            options={'verbose_name': 'Vente de garde', 'verbose_name_plural': 'Ventes de garde'},
        ),
        migrations.AddField(
            model_name='phgardestock',
            name='quantite_restante',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantité restante'),
        ),
        migrations.AddField(
            model_name='phgardestock',
            name='quantite_vendue',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité vendue'),
        ),
    ]
