# Generated by Django 5.1.7 on 2025-06-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_garde', '0008_alter_phgardestock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phgardeproduit',
            options={'ordering': ['nom_produit'], 'verbose_name': 'PhGardeProduit', 'verbose_name_plural': 'PhGardeProduits'},
        ),
        migrations.AddField(
            model_name='phgardefacturepharmacie',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
    ]
