# Generated by Django 5.1.7 on 2025-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_docteur', models.CharField(max_length=200, verbose_name='Nom du Docteur')),
                ('nom_personne', models.CharField(max_length=255, verbose_name='Nom complet de la personne concernée')),
                ('jour_rdv', models.PositiveIntegerField()),
                ('mois_rdv', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=1, verbose_name='Mois du rendez-vous')),
                ('annee_rdv', models.PositiveSmallIntegerField(default=2025, verbose_name='Année du rendez-vous')),
                ('heure_rdv', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('statut', models.CharField(choices=[('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('en_attente', 'En attente')], default='en_attente', max_length=15, verbose_name='Statut du rendez-vous')),
                ('numero_dossier', models.CharField(blank=True, max_length=100, null=True, verbose_name='numero du dossier')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
            },
        ),
    ]
