# Generated by Django 5.1.7 on 2025-05-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0002_rendezvous_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='actes',
            field=models.TextField(blank=True, null=True, verbose_name='Actes réalisés ou prévus'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro du dossier'),
        ),
    ]
