# Generated by Django 5.1.7 on 2025-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0003_rendezvous_actes_alter_rendezvous_numero_dossier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='actes',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='acte',
            field=models.BooleanField(default=False, verbose_name='Actes réalisés ou prévus'),
        ),
    ]
