# Generated by Django 5.1.7 on 2025-04-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pansement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pansement',
            name='commentaire',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire'),
        ),
    ]
