# Generated by Django 5.1.7 on 2025-04-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pansement', '0002_pansement_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pansement',
            name='penseur',
        ),
        migrations.AddField(
            model_name='pansement',
            name='panseur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Panseur'),
        ),
    ]
