# Generated by Django 5.1.7 on 2025-05-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pansement', '0003_remove_pansement_penseur_pansement_panseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pansement',
            name='nom_personne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet de la personne concernée'),
        ),
    ]
