# Generated by Django 5.1.7 on 2025-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pansement', '0005_pansement_save_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pansement',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
    ]
