# Generated by Django 5.1.7 on 2025-06-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pansement', '0005_pansement_save_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pansement',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Obseration'),
        ),
    ]
