# Generated by Django 5.1.7 on 2025-06-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pansement', '0006_pansement_numero_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pansement',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient'),
        ),
    ]
