# Generated by Django 5.1.7 on 2025-06-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pansement', '0007_alter_pansement_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pansement',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Obseration'),
        ),
    ]
