# Generated by Django 5.1.7 on 2025-04-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0009_patient_assistant_patient_medecin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.CharField(max_length=255, verbose_name='Examen')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('nature_examen', models.CharField(blank=True, choices=[('Examen fait maison', 'Examen fait maison'), ("Examen fait à l'extérieur", "Examen fait à l'extérieur")], max_length=50, null=True, verbose_name="Nature de l'examen ")),
                ('prescripteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prescripteur')),
                ('preleveur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Préleveur')),
                ('technicien', models.CharField(blank=True, max_length=100, null=True, verbose_name='Technicien(ne)')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='ExamenCytologieEcbu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecbu_culot', models.CharField(max_length=255, verbose_name='ECBU Culot')),
                ('ecbu_couleur', models.CharField(max_length=255, verbose_name='ECBU couleur')),
                ('cyto_ce', models.CharField(max_length=255, verbose_name='Cyto CE')),
                ('cyto_leuco', models.CharField(max_length=255, verbose_name='Cyto Leuco')),
                ('cyto_cylendre', models.CharField(max_length=255, verbose_name='Cyto Cylendre')),
                ('cyto_cristaux', models.CharField(max_length=255, verbose_name='Cyto Cristaux')),
                ('cyto_h', models.CharField(max_length=255, verbose_name='Cyto H')),
                ('cyto_gram', models.CharField(max_length=255, verbose_name='Cyto Gram')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'ExamenCytologieEcbu',
                'verbose_name_plural': 'ExamensCytologieEcbu',
            },
        ),
        migrations.CreateModel(
            name='ExamenCytologiePv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_secretion', models.CharField(max_length=255, verbose_name='PV Sécrétion')),
                ('pv_couleur', models.CharField(max_length=255, verbose_name='PV Couleur')),
                ('pv_odeur', models.CharField(max_length=255, verbose_name='PV Odeur')),
                ('cyto_ce', models.CharField(max_length=255, verbose_name='Cyto CE')),
                ('cyto_leuco', models.CharField(max_length=255, verbose_name='Cyto Leuco')),
                ('cyto_cc', models.CharField(max_length=255, verbose_name='Cyto CC')),
                ('cyto_levure', models.CharField(max_length=255, verbose_name='Cyto levure')),
                ('cyto_h', models.CharField(max_length=255, verbose_name='Cyto H')),
                ('cyto_tv', models.CharField(max_length=255, verbose_name='Cyto TV')),
                ('cyto_gram', models.CharField(max_length=255, verbose_name='Cyto Gram')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'ExamenCytologiePv',
                'verbose_name_plural': 'ExamensCytologiePv',
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.TextField(verbose_name='Examen')),
                ('resultat', models.TextField(verbose_name='Résultat')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Resultat',
                'verbose_name_plural': 'Resultats',
            },
        ),
    ]
