# Generated by Django 5.1.7 on 2025-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0002_examen_nom_personne_examencytologieecbu_nom_personne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AddField(
            model_name='examencytologieecbu',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AddField(
            model_name='examencytologiepv',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date et heure de création'),
        ),
    ]
