# Generated by Django 5.1.7 on 2025-03-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=50, verbose_name='Numéro de dossier')),
                ('actes', models.CharField(max_length=255, verbose_name='Actes')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('medecin', models.CharField(max_length=100, verbose_name='Médecin')),
                ('aides', models.TextField(verbose_name='Aides médecins')),
                ('instrumentiste', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrumentiste')),
                ('penseur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Penseur')),
                ('anesthesiste', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anesthésiste')),
                ('observation', models.TextField(verbose_name='Observation')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'BlocOpératoire',
                'verbose_name_plural': 'BlocOpératoires',
            },
        ),
    ]
