# Generated by Django 5.1.7 on 2025-04-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocoperatoire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocoperatoire',
            name='numero_dossier',
        ),
    ]
