# Generated by Django 5.1.7 on 2025-04-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocoperatoire', '0002_remove_blocoperatoire_numero_dossier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocoperatoire',
            name='penseur',
        ),
        migrations.AddField(
            model_name='blocoperatoire',
            name='panseur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Panseur'),
        ),
    ]
