# Generated by Django 5.1.7 on 2025-04-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocoperatoire', '0003_remove_blocoperatoire_penseur_blocoperatoire_panseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocoperatoire',
            name='aides',
            field=models.TextField(blank=True, null=True, verbose_name='Aides médecins'),
        ),
        migrations.AlterField(
            model_name='blocoperatoire',
            name='medecin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin'),
        ),
        migrations.AlterField(
            model_name='blocoperatoire',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
    ]
