# Generated by Django 5.1.7 on 2025-06-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocoperatoire', '0006_blocoperatoire_save_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocoperatoire',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
    ]
