# Generated by Django 5.1.7 on 2025-03-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(choices=[('Admin', 'Administrateur'), ('Médecin', 'Médecin'), ('Pharmacien(ne)', 'Pharmacien(ne)'), ('Réceptioniste', 'Réceptioniste'), ('Infirmier(e)', 'Infirmier(e)')], max_length=50, verbose_name='Fonction'),
        ),
    ]
