# Generated by Django 5.1.7 on 2025-03-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0003_alter_personnel_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
