# Generated by Django 5.1.7 on 2025-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0004_personnel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(choices=[('Admin', 'Administrateur'), ('Info-comptable', 'Info-comptable'), ('Médecin', 'Médecin'), ('Pharmacien(ne)', 'Pharmacien(ne)'), ('Cassier(e)', 'Cassier(e)'), ('Réceptioniste', 'Réceptioniste'), ('Infirmier(e)', 'Infirmier(e)'), ('Laborantin(ne)', 'Laborantin(ne)'), ('Instrumentiste', 'Instrumentiste'), ('Penseur', 'Penseur'), ('Anesthesiste', 'Anesthesiste'), ('Aides-soignante', 'Aides-soignante'), ('Gestionnaire-phamarcie', 'Gestionnaire-pharmacie')], max_length=50, verbose_name='Fonction'),
        ),
    ]
