# Generated by Django 5.1.7 on 2025-04-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0005_alter_personnel_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='last_name',
        ),
    ]
