# Generated by Django 5.1.7 on 2025-04-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0006_remove_personnel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='email',
        ),
    ]
