# Generated by Django 5.1.7 on 2025-04-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0007_remove_personnel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom'),
        ),
    ]
