# Generated by Django 5.1.7 on 2025-04-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0008_personnel_email_personnel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='email',
        ),
    ]
