# Generated by Django 5.1.7 on 2025-03-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('nombre_jours', models.PositiveIntegerField(verbose_name='Nombre de jours')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
            },
        ),
    ]
