# Generated by Django 5.1.7 on 2025-04-19 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0002_hospitalisation_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='date_admission',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'admission"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='nombre_jours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de jours'),
        ),
    ]
