# Generated by Django 5.1.7 on 2025-06-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0003_hospitalisation_date_admission_and_more'),
        ('personnels', '0010_personnel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='nom_personne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet de la personne concernée'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
    ]
