# Generated by Django 5.1.7 on 2025-05-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0003_hospitalisation_date_admission_and_more'),
        ('personnels', '0010_personnel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='save_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personnels.personnel', verbose_name='Agent'),
        ),
    ]
