# Generated by Django 5.1.7 on 2025-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0004_hospitalisation_save_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='nom_personne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet de la personne concernée'),
        ),
    ]
