# Generated by Django 5.1.7 on 2025-06-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0004_hospitalisation_nom_personne_and_more'),
        ('personnels', '0010_personnel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient'),
        ),
    ]
