# Generated by Django 5.1.7 on 2025-03-19 09:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutresDepenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=500, verbose_name='Autres Dépenses')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'AutresDepense',
                'verbose_name_plural': 'AutresDepenses',
            },
        ),
        migrations.CreateModel(
            name='FactureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la Facture')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('somme_verse', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme versée')),
                ('total_somme_verse', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total des sommes versées')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Reste à payer')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnels.personnel', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Facture Caisse',
                'verbose_name_plural': 'Factures Caisse',
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('blocoperatoire', 'Bloc Opératoire'), ('laboratoire', 'Laboratoire'), ('viol', 'Viol'), ('vaccin', 'Vaccin'), ('pansement', 'Pansement'), ('hospitalisation', 'Hospitalisation'), ('echographie', 'Échographie'), ('consultation simple', 'Consultation Simple'), ('consultation prénatale', 'Consultation Prénatale'), ('consultation ORL', 'Consultation ORL'), ('MTO', 'MTO')], max_length=50, verbose_name='Motif du paiement')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caisse_set', to='caisse.facturecaisse', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
            },
        ),
    ]
