# Generated by Django 5.1.7 on 2025-03-20 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_facturecaisse_avance_facturecaisse_last_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturecaisse',
            name='reste_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer'),
        ),
    ]
