# Generated by Django 5.1.7 on 2025-03-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_alter_facturecaisse_reste_a_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturecaisse',
            name='avance',
        ),
        migrations.RemoveField(
            model_name='facturecaisse',
            name='last_updated_date',
        ),
        migrations.RemoveField(
            model_name='facturecaisse',
            name='nombre_versements',
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Reste à payer'),
        ),
        migrations.DeleteModel(
            name='FactureAvanceCaisse',
        ),
    ]
