# Generated by Django 5.1.7 on 2025-03-20 00:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_remove_facturecaisse_avance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecaisse',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avance temporaire'),
        ),
        migrations.CreateModel(
            name='FactureAvanceCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant versé')),
                ('date_versement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='caisse.facturecaisse', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Avance Caisse',
                'verbose_name_plural': 'Avances Caisse',
            },
        ),
    ]
