# Generated by Django 5.1.7 on 2025-03-20 01:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_facturecaisse_avance_factureavancecaisse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturecaisse',
            name='somme_verse',
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total à payer'),
        ),
    ]
