# Generated by Django 5.1.7 on 2025-03-20 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_remove_facturecaisse_somme_verse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturecaisse',
            name='avance',
        ),
        migrations.AddField(
            model_name='facturecaisse',
            name='somme_verse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme versée'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.DeleteModel(
            name='FactureAvanceCaisse',
        ),
    ]
