# Generated by Django 5.1.7 on 2025-03-20 06:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_remove_facturecaisse_avance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecaisse',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avance'),
        ),
        migrations.AddField(
            model_name='facturecaisse',
            name='nombre_versements',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de paiements'),
        ),
        migrations.CreateModel(
            name='FactureAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date_versement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de versement')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.facturecaisse', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Avance Facture',
                'verbose_name_plural': 'Avances Facture',
            },
        ),
    ]
