# Generated by Django 5.1.7 on 2025-03-20 07:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0008_facturecaisse_avance_facturecaisse_nombre_versements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='factureavance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facturecaisse',
            options={'verbose_name': 'Facture Caisse', 'verbose_name_plural': 'Factures Caisses'},
        ),
        migrations.AddField(
            model_name='factureavance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='facturecaisse',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de paiement'),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.facturecaisse', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='factureavance',
            name='date_versement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement'),
        ),
        migrations.AlterField(
            model_name='factureavance',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='caisse.facturecaisse', verbose_name='Facture'),
        ),
        migrations.AlterField(
            model_name='factureavance',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant versé'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='nombre_versements',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de paiements effectués'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='reste_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='somme_verse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme versée'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='total_somme_verse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total des sommes versées'),
        ),
    ]
