# Generated by Django 5.1.7 on 2025-03-20 08:07

import caisse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0009_alter_caisse_options_alter_factureavance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecaisse',
            name='numero_facture',
            field=models.CharField(default=caisse.models.generate_unique_numero_facture, max_length=25, unique=True, verbose_name='Numéro de dossier'),
        ),
    ]
