# Generated by Django 5.1.7 on 2025-03-20 08:32

import caisse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0010_facturecaisse_numero_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturecaisse',
            name='numero_facture',
            field=models.CharField(default=caisse.models.generate_unique_numero_facture, max_length=25, unique=True, verbose_name='Numéro de facture'),
        ),
    ]
