# Generated by Django 5.1.7 on 2025-03-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0011_alter_facturecaisse_numero_facture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factureavance',
            options={'verbose_name': 'Avance', 'verbose_name_plural': 'Avances'},
        ),
        migrations.AlterField(
            model_name='factureavance',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='caisse.facturecaisse', verbose_name='Numéro de facture'),
        ),
    ]
