# Generated by Django 5.1.7 on 2025-03-30 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0012_alter_factureavance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturecaisse',
            name='paye',
        ),
        migrations.AddField(
            model_name='facturecaisse',
            name='statut_paiement',
            field=models.CharField(choices=[('non_payee', 'Non Payée'), ('partiellement_payee', 'Partiellement Payée'), ('payee', 'Payée')], default='non_payee', max_length=20, verbose_name='Statut de paiement'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='reste_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='somme_verse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme versée'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='total_somme_verse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total des sommes versées'),
        ),
    ]
