# Generated by Django 5.1.7 on 2025-03-30 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0013_remove_facturecaisse_paye_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturecaisse',
            name='statut_paiement',
        ),
        migrations.AddField(
            model_name='facturecaisse',
            name='paye',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='reste_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='somme_verse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme versée'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='total_somme_verse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total des sommes versées'),
        ),
    ]
