# Generated by Django 5.1.7 on 2025-04-11 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0014_remove_facturecaisse_statut_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalierCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caissier', models.CharField(max_length=255, verbose_name='Nom complet du caissier/caissière')),
                ('total_encaisse', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total encaissé')),
                ('depense', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dépense')),
                ('reste', models.DecimalField(decimal_places=2, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date du rapport')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'Rapport journalier de caisse',
                'verbose_name_plural': 'Rapports journaliers de caisse',
            },
        ),
    ]
