# Generated by Django 5.1.7 on 2025-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0016_alter_rapportjournaliercaisse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='motif',
            field=models.CharField(max_length=255, verbose_name='Motif du paiement'),
        ),
    ]
