# Generated by Django 5.1.7 on 2025-05-08 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0017_alter_caisse_motif'),
        ('patients', '0010_patient_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecaisse',
            name='nom_personne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet de la personne concernée'),
        ),
        migrations.AlterField(
            model_name='facturecaisse',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient'),
        ),
    ]
