# Generated by Django 5.1.7 on 2025-06-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0019_rapportjournaliercaisse_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecaisse',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
    ]
