# Generated by Django 5.1.7 on 2025-06-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet du patient')),
                ('numero_dossier', models.CharField(max_length=100, verbose_name='Numéro de dossier')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif de la visite')),
                ('type', models.CharField(max_length=100, verbose_name='Type de prestation')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
            },
        ),
    ]
