# Generated by Django 5.1.7 on 2025-04-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccin',
            name='numero_dossier',
        ),
    ]
