# Generated by Django 5.1.7 on 2025-05-04 12:06

import caisse_garde.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0009_patient_assistant_patient_medecin'),
        ('personnels', '0010_personnel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutresDepensesGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=500, verbose_name='Autres Dépenses')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'AutresDepenseGarde',
                'verbose_name_plural': 'AutresDepenses Garde',
            },
        ),
        migrations.CreateModel(
            name='RapportJournalierCaisseGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caissier', models.CharField(max_length=255, verbose_name='Nom complet du caissier/caissière')),
                ('total_encaisse', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total encaissé')),
                ('depense', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dépense')),
                ('reste', models.DecimalField(decimal_places=2, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du rapport')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'Rapport journalier de caisse garde',
                'verbose_name_plural': 'Rapports journaliers de caisse garde',
            },
        ),
        migrations.CreateModel(
            name='FactureCaisseGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(default=caisse_garde.models.generate_unique_numero_facture, max_length=25, unique=True, verbose_name='Numéro de facture')),
                ('facture_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la Facture')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('somme_verse', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme versée')),
                ('avance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avance')),
                ('total_somme_verse', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total des sommes versées')),
                ('reste_a_payer', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer')),
                ('nombre_versements', models.PositiveIntegerField(default=0, verbose_name='Nombre de paiements effectués')),
                ('last_updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière mise à jour')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnels.personnel', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Facture Caisse Garde',
                'verbose_name_plural': 'Factures Caisses Garde',
            },
        ),
        migrations.CreateModel(
            name='FactureAvanceGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant versé')),
                ('date_versement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='caisse_garde.facturecaissegarde', verbose_name='Numéro de facture')),
            ],
            options={
                'verbose_name': 'Avance Garde',
                'verbose_name_plural': 'Avances Garde',
            },
        ),
        migrations.CreateModel(
            name='CaisseGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif du paiement')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de paiement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse_garde.facturecaissegarde', verbose_name='Facture')),
            ],
        ),
    ]
