# Generated by Django 5.1.7 on 2025-05-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse_garde', '0002_facturecaissegarde_nom_personne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournaliercaissegarde',
            name='commentaire',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire'),
        ),
    ]
