# Generated by Django 5.1.7 on 2025-03-19 09:14

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
                ('nationalite', django_countries.fields.CountryField(default='CG', max_length=2, verbose_name='Nationalité')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('situation_matrimoniale', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve')], max_length=1, verbose_name='Situation matrimoniale')),
                ('type_personne', models.CharField(choices=[('adulte', 'Adulte'), ('enfant', 'Enfant'), ('nouveau-né', 'Nouveau-né')], max_length=10, verbose_name='Type de personne')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=25, null=True, verbose_name='groupe sanguin')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('numero_dossier', models.CharField(max_length=25, verbose_name='Numéro de dossier')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
