# Generated by Django 5.1.7 on 2025-03-19 09:40

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='numero_dossier',
            field=models.CharField(default=patients.models.generate_unique_dossier, max_length=25, unique=True, verbose_name='Numéro de dossier'),
        ),
    ]
