# Generated by Django 5.1.7 on 2025-03-21 08:52

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_numero_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationalite',
            field=django_countries.fields.CountryField(blank=True, default='CG', max_length=2, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Téléphone'),
        ),
    ]
