# Generated by Django 5.1.7 on 2025-03-21 08:53

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_adresse_alter_patient_nationalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nationalite',
            field=django_countries.fields.CountryField(default='CG', max_length=2, verbose_name='Nationalité'),
        ),
    ]
