# Generated by Django 5.1.7 on 2025-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_groupe_sanguin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse_personne_contacter',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse personne à contacter'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lien',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien'),
        ),
        migrations.AddField(
            model_name='patient',
            name='niveau_instruction',
            field=models.CharField(blank=True, choices=[('Illttré(e)', 'Illetré(e)'), ('Primaire', 'Primaire'), ('Secondaire', 'Secondaire'), ('Universitaire', 'Universitaire')], max_length=50, null=True, verbose_name="Niveau d'instruction"),
        ),
        migrations.AddField(
            model_name='patient',
            name='personne_contacter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personne à contacter si besoin'),
        ),
        migrations.AddField(
            model_name='patient',
            name='piece_identite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Pièce d'identité n°"),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone_personne_contacter',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Téléphone personne à contacter'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='situation_matrimoniale',
            field=models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve'), ('S', 'Séparé(e)')], max_length=1, verbose_name='Situation matrimoniale'),
        ),
    ]
