# Generated by Django 5.1.7 on 2025-04-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_adresse_personne_contacter_patient_lien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adresse_personne_contacter',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse personne à contacter si besoin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone_personne_contacter',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Téléphone personne à contacter si besoin'),
        ),
    ]
