# Generated by Django 5.1.7 on 2025-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_adresse_personne_contacter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('Neutre', 'Neutre'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=15, null=True, verbose_name='Groupe sanguin'),
        ),
    ]
