# Generated by Django 5.1.7 on 2025-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_groupe_sanguin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assistant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assistant(e)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medecin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Médecin'),
        ),
    ]
