# Generated by Django 5.1.7 on 2025-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='situation_matrimoniale',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf/Veuve', 'Veuf/Veuve'), ('Séparé(e)', 'Séparé(e)')], max_length=25, verbose_name='Situation matrimoniale'),
        ),
    ]
