# Generated by Django 5.1.7 on 2025-05-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0011_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_consultation', models.CharField(blank=True, choices=[('consultation simple', 'Consultation Simple'), ('consultation prénatale', 'Consultation Prénatale'), ('consultation ORM', 'Consultation ORL')], max_length=100, null=True, verbose_name='Type de consultation')),
                ('nom_personne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet de la personne concernée')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('medecin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin traitant')),
                ('assistant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assistant(e)')),
                ('commentaire', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire')),
                ('motif_consultation', models.TextField(blank=True, null=True, verbose_name='Motif de consultation')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, null=True, verbose_name='TA (Tension artérielle)')),
                ('pouls', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pouls (bpm)')),
                ('saturation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Saturation (%)')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Taille (m)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('tdr', models.BooleanField(default=False, verbose_name='TDR positif (si fièvre)')),
                ('glycemie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Glycémie')),
                ('alb_sucre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alb/Sucre (si grossesse)')),
                ('atcd_socioeconomique', models.BooleanField(default=False, verbose_name='Situation socioéconomique difficile')),
                ('atcd_chomage', models.BooleanField(default=False, verbose_name='Chômage')),
                ('atcd_violence_domestique', models.BooleanField(default=False, verbose_name='Violence domestique')),
                ('atcd_prison', models.BooleanField(default=False, verbose_name='Passage en prison')),
                ('atcd_arret_ecole', models.BooleanField(default=False, verbose_name='Arrêt de la scolarisation')),
                ('atcd_victime_guerre', models.BooleanField(default=False, verbose_name='Victime de guerre')),
                ('suivi_medecin', models.TextField(blank=True, null=True, verbose_name='Suivi du médecin')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire général')),
                ('prescripteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prescripteur')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='consultation.consultation', verbose_name='Consultation liée')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.TextField(verbose_name='Nom du médicament')),
                ('posologie', models.CharField(max_length=200, verbose_name='Posologie')),
                ('duree', models.CharField(max_length=100, verbose_name='Durée du traitement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_prescription', models.DateTimeField(auto_now_add=True, verbose_name='Date de prescription')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='consultation.ordonnance', verbose_name='Ordonnance liée')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
            },
        ),
    ]
