# Generated by Django 5.1.7 on 2025-03-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_alter_patient_nationalite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_consultation', models.CharField(choices=[('consultation simple', 'Consultation Simple'), ('consultation prénatale', 'Consultation Prénatale'), ('consultation ORM', 'Consultation ORL')], max_length=100, verbose_name='Type de consultation')),
                ('numero_dossier', models.CharField(max_length=50, verbose_name='Numéro de dossier')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('medecin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin')),
                ('assistant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assistant(e)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
    ]
