# Generated by Django 5.1.7 on 2025-05-12 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('patients', '0011_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient'),
            preserve_default=False,
        ),
    ]
