# Generated by Django 5.1.7 on 2025-03-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='numero_dossier',
        ),
    ]
