# Generated by Django 5.1.7 on 2025-06-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
    ]
