# Generated by Django 5.1.7 on 2025-04-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultation_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='alb_sucre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alb/Sucre (si grossesse)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='atcd_arret_ecole',
            field=models.BooleanField(default=False, verbose_name='Arrêt de la scolarisation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='atcd_chomage',
            field=models.BooleanField(default=False, verbose_name='Chômage'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='atcd_prison',
            field=models.BooleanField(default=False, verbose_name='Passage en prison'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='atcd_socioeconomique',
            field=models.BooleanField(default=False, verbose_name='Situation socioéconomique difficile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='atcd_victime_guerre',
            field=models.BooleanField(default=False, verbose_name='Victime de guerre'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='atcd_violence_domestique',
            field=models.BooleanField(default=False, verbose_name='Violence domestique'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='glycemie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Glycémie'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='motif_consultation',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de consultation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pouls',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pouls (bpm)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='saturation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Saturation (%)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='taille',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Taille (m)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tdr',
            field=models.BooleanField(default=False, verbose_name='TDR positif (si fièvre)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tension_arterielle',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TA (Tension artérielle)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medecin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin traitant'),
        ),
    ]
