# Generated by Django 5.1.7 on 2025-04-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_consultation_alb_sucre_consultation_atcd_arret_ecole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='suivi_medecin',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi du médecin'),
        ),
    ]
