# Generated by Django 5.1.7 on 2025-04-30 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultation_suivi_medecin'),
        ('patients', '0009_patient_assistant_patient_medecin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('posologie', models.CharField(max_length=200, verbose_name='Posologie')),
                ('duree', models.CharField(max_length=100, verbose_name='Durée du traitement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('prescripteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prescripteur')),
                ('date_prescription', models.DateTimeField(auto_now_add=True, verbose_name='Date de prescription')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='consultation.consultation', verbose_name='Consultation liée')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
            },
        ),
    ]
