# Generated by Django 5.1.7 on 2025-04-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_traitement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traitement',
        ),
    ]
