# Generated by Django 5.1.7 on 2025-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_ordonnance_traitement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='patient',
        ),
        migrations.AlterField(
            model_name='traitement',
            name='medicament',
            field=models.TextField(verbose_name='Nom du médicament'),
        ),
    ]
