# Generated by Django 5.1.7 on 2025-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_remove_ordonnance_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='nom_personne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet de la personne concernée'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type_consultation',
            field=models.CharField(blank=True, choices=[('consultation simple', 'Consultation Simple'), ('consultation prénatale', 'Consultation Prénatale'), ('consultation ORM', 'Consultation ORL')], max_length=100, null=True, verbose_name='Type de consultation'),
        ),
    ]
