# Generated by Django 5.1.7 on 2025-04-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viol',
            name='numero_dossier',
        ),
    ]
