# Generated by Django 5.1.7 on 2025-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viol', '0002_remove_viol_numero_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='viol',
            name='commentaire',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Commentaire'),
        ),
    ]
