# Generated by Django 5.1.7 on 2025-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viol', '0003_viol_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viol',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Obseration'),
        ),
    ]
