# Generated by Django 5.1.7 on 2025-06-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viol', '0006_viol_save_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='viol',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de dossier'),
        ),
    ]
